library(ggplot2)
library(tidyverse)
data<-readxl::read_xlsx("book1.xlsx")
names(data)<-c("Cluster", "Agency", "Year", "ParttimeorFulltime", "Gender", "Headcount")
summary(data)
sum(is.na(data))
png(filename = "Employment_Numbers.png", height = 600, width = 600)
genderanalysis<-data%>%group_by(Year)%>%summarise(total=sum(Headcount))
ggplot(genderanalysis, aes(x=Year, y=total))+geom_line( col="indianred3", size=1.5)+theme_minimal()+labs(y="Trend in total employment numbers in each year", x="Year", title = "Total employment numbers vs Year")+theme(panel.grid.major = element_blank())
dev.off()
genderanalysis<-data%>%group_by(Gender, Year)%>%summarise(total=sum(Headcount))
png(filename = "Employment_Numbers_by_Gender.png", height = 600, width = 600)
ggplot(genderanalysis, aes(x=Year, y=total))+geom_line( size=1.5, aes(col=Gender))+theme_minimal()+labs(y="Trend in total employment numbers in each year", x="Year", title = "Total employment numbers vs Year")+theme(panel.grid.major = element_blank())
dev.off()
parttimeanalysis<-data%>%filter (Year==2018)%>%group_by( Cluster,ParttimeorFulltime)%>%summarise(total=sum(Headcount))%>%ungroup()%>%group_by(Cluster)%>%mutate(prop=total/sum(total), lbl=scales::percent(prop))
png(filename = "Proportion_of_PT_FT.png", height = 600, width = 600)
ggplot(parttimeanalysis, aes(x=Cluster, y=prop, fill=ParttimeorFulltime))+geom_bar(stat="identity", position = "fill")+scale_fill_brewer(palette = "Set2")+geom_text(aes(label=lbl), size=5, position = position_stack(vjust = 0.5))+scale_y_continuous(breaks = seq(0,1,.2), label=scales::percent)+theme(axis.text.x = element_text(angle=45, hjust=1))+labs(y="percent", fill="FT/PT", x="Cluster", title = "Proportion of PT/FT workers in various clusters")
dev.off()
clusterparttime<-data%>%filter (Year==2018)%>%group_by( ParttimeorFulltime,Cluster, Gender)%>%summarise(total=sum(Headcount))%>%ungroup()%>%group_by(Cluster, ParttimeorFulltime)%>%mutate(prop=total/sum(total), lbl=scales::percent(prop))
png(filename = "Proportion_of_PT_FT_gender.png", height = 800, width = 600)
ggplot(clusterparttime, aes(x=ParttimeorFulltime, y=prop, fill=Gender))+geom_bar(stat="identity", position = "fill")+facet_grid(~Cluster)+scale_fill_brewer(palette = "Set2")+geom_text(aes(label=lbl), size=5, position = position_stack(vjust = 0.5))+scale_y_continuous(breaks = seq(0,1,.2), label=scales::percent)+theme(axis.text.x = element_text(angle=45, hjust=1))+labs(y="percent", fill="Gender", x="Cluster", title = "Proportion of PT/FT workers in various clusters")    
dev.off()


fouryearparttimeanalysis<-data%>%group_by( Year, Cluster,ParttimeorFulltime)%>%summarise(total=sum(Headcount))%>%ungroup()%>%group_by(Year, Cluster)%>%mutate(prop=total/sum(total), lbl=scales::percent(prop))
png(filename = "Proportion_CLUSTERS_PT_FT.png", height = 800, width = 600)
ggplot(fouryearparttimeanalysis)+geom_bar(aes(x=Year, y=prop, fill=ParttimeorFulltime), stat="identity", position = "fill")+facet_grid(~Cluster)+theme(axis.text.x = element_text(angle=45, hjust=1, size = 8), strip.text.x = element_text(size=7))+scale_y_continuous(breaks = seq(0,1,.2), label=scales::percent)
dev.off()
yearclustergenderparttime<-data%>%group_by( Year, ParttimeorFulltime,Cluster, Gender)%>%summarise(total=sum(Headcount))%>%ungroup()%>%group_by(Year,Cluster, ParttimeorFulltime)%>%mutate(prop=total/sum(total), lbl=scales::percent(prop))
png(filename = "Proportion_CLUSTERS_PT_FT_gender.png", height = 800, width = 1200)
ggplot(yearclustergenderparttime)+geom_bar(aes(x=Year, y=prop, fill=Gender), stat="identity", position = "fill")+facet_grid(ParttimeorFulltime~Cluster)+theme(axis.text.x = element_text(angle=45, hjust=1, size = 8), strip.text.x = element_text(size=7))+scale_y_continuous(breaks = seq(0,1,.2), label=scales::percent)
dev.off()
nested<-fouryearparttimeanalysis%>%filter(ParttimeorFulltime=="Part-Time")%>%group_by(Cluster)%>% nest()
model<-nested%>%mutate(model=map(data, ~lm(formula = prop~Year, data=.x)))
dataaaa<-data.frame(Year=2025)

for(i in 1:10){
  models<-model$model[[i]]
  b<-predict(models, dataaaa)
  print(b)
}
year_2025<-data.frame(year_2025=c(0.5223705,0,0.5105916, 0.365941,0,0.12, 0.16, 0.12, 0.21, 0.135))
model<-cbind(model, year_2025)
modeld<-data.frame(model$Cluster, prop_of_part_time_in_2025=model$year_2025)
write.csv(modeld, file="model.csv")
modeld
